<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->products() as $row) {
            $category = Category::where('slug', $row['category'])->firstOrFail();
            $brand = $row['brand'] ?? null
                ? Brand::where('slug', $row['brand'])->first()
                : null;

            Product::updateOrCreate(
                ['slug' => Str::slug($row['name'])],
                [
                    'category_id' => $category->id,
                    'brand_id' => $brand?->id,
                    'name' => $row['name'],
                    'description' => $row['description'],
                    'price' => $row['price'],
                    'compare_at_price' => $row['compare'] ?? null,
                    'emoji' => $row['emoji'],
                    'image_url' => '/img/products/'.Str::slug($row['name']).'.jpg',
                    'badge' => $row['badge'] ?? null,
                    'featured' => $row['featured'] ?? false,
                    'is_deal' => $row['is_deal'] ?? false,
                    'rating' => $row['rating'],
                    'reviews_count' => $row['reviews'],
                    'rating_chips' => $row['chips'] ?? null,
                    'options' => $row['options'] ?? null,
                    'delivery_standard' => $row['standard'] ?? true,
                    'delivery_pickup' => $row['pickup'] ?? true,
                    'stock' => $row['stock'] ?? 120,
                ],
            );
        }
    }

    private function products(): array
    {
        return [
            // ---------------------------------------------------------------- Sport
            [
                'name' => 'Smart Watch WH22-6 Fitness Tracker',
                'category' => 'sport',
                'brand' => 'xiaomi',
                'emoji' => '⌚',
                'price' => 454.00,
                'badge' => 'top',
                'rating' => 4.80,
                'reviews' => 126,
                'options' => ['sizes' => ['41mm', '45mm'], 'colors' => ['Silver', 'Midnight']],
                'description' => 'Always-on retina display, 7-day battery, heart-rate and sleep tracking with 100+ sport modes.',
            ],
            [
                'name' => 'Tennis Rackets for Beginners',
                'category' => 'sport',
                'brand' => 'wilson',
                'emoji' => '🎾',
                'price' => 30.99,
                'rating' => 4.50,
                'reviews' => 84,
                'description' => 'Lightweight graphite frame with a generous sweet spot — the perfect first racket for court newcomers.',
            ],
            [
                'name' => 'Premium Boxing Gloves for Pro Training',
                'category' => 'sport',
                'brand' => 'adidas',
                'emoji' => '🥊',
                'price' => 196.84,
                'compare' => 276.57,
                'is_deal' => true,
                'rating' => 4.70,
                'reviews' => 212,
                'options' => ['sizes' => ['12 oz', '14 oz', '16 oz'], 'colors' => ['White', 'Black']],
                'description' => 'Multi-layer foam padding with a locked-in wrist wrap, built for heavy bag and sparring sessions.',
            ],
            [
                'name' => 'Club Kit 1 Recurve Archery Bow',
                'category' => 'sport',
                'brand' => 'demix',
                'emoji' => '🏹',
                'price' => 48.99,
                'rating' => 4.40,
                'reviews' => 57,
                'description' => 'Complete recurve starter kit with riser, limbs, string and finger tab — takedown design for easy transport.',
            ],
            [
                'name' => 'Lightweight White Nike Training Shoes',
                'category' => 'sport',
                'brand' => 'nike',
                'emoji' => '👟',
                'price' => 210.00,
                'badge' => 'top',
                'rating' => 4.60,
                'reviews' => 340,
                'options' => ['sizes' => ['7', '8', '9', '10', '11'], 'colors' => ['White', 'Grey']],
                'description' => 'Breathable mesh upper with responsive foam cushioning for training days and everyday miles.',
            ],
            [
                'name' => 'Pro Grip Badminton Shuttlecocks (12 Pack)',
                'category' => 'sport',
                'brand' => 'yonex',
                'emoji' => '🏸',
                'price' => 12.99,
                'rating' => 4.30,
                'reviews' => 45,
                'description' => 'Tournament-grade feather shuttlecocks with consistent flight and durable cork bases.',
            ],
            [
                'name' => 'Adidas Training Duffel Bag',
                'category' => 'sport',
                'brand' => 'adidas',
                'emoji' => '🎒',
                'price' => 64.50,
                'rating' => 4.50,
                'reviews' => 98,
                'description' => '30L gym duffel with ventilated shoe pocket, water-resistant base and adjustable padded strap.',
            ],
            [
                'name' => 'Asics Gel Quantum Running Shoes',
                'category' => 'sport',
                'brand' => 'asics',
                'emoji' => '👟',
                'price' => 139.99,
                'compare' => 179.99,
                'is_deal' => true,
                'rating' => 4.60,
                'reviews' => 154,
                'options' => ['sizes' => ['7', '8', '9', '10', '11'], 'colors' => ['Silver', 'Navy']],
                'description' => 'GEL® cushioning in the rearfoot and a springy midsole for long, comfortable road runs.',
            ],
            [
                'name' => 'Adjustable Dumbbell Set 20 kg',
                'category' => 'sport',
                'brand' => 'demix',
                'emoji' => '🏋️',
                'price' => 189.00,
                'rating' => 4.80,
                'reviews' => 76,
                'standard' => true,
                'pickup' => false,
                'description' => 'Space-saving adjustable dumbbells from 2.5 kg to 20 kg with quick-select dial locks.',
            ],

            // ---------------------------------------------------------------- Fashion
            [
                'name' => 'Nike White Thermo-Fit Pullover Training Hoodie',
                'category' => 'fashion',
                'brand' => 'nike',
                'emoji' => '🧥',
                'price' => 154.95,
                'featured' => true,
                'rating' => 4.70,
                'reviews' => 412,
                'chips' => [4.7, 4.4, 5.0],
                'options' => ['sizes' => ['S', 'M', 'L', 'XL'], 'colors' => ['White', 'Black', 'Purple']],
                'description' => 'Thermal knit that traps heat without the bulk — thumbholes, a cross-zip neck and reflective details for cold-weather sessions.',
            ],
            [
                'name' => 'Columbia Rapid Shield Windbreaker',
                'category' => 'fashion',
                'brand' => 'columbia',
                'emoji' => '🧥',
                'price' => 89.99,
                'rating' => 4.50,
                'reviews' => 187,
                'options' => ['sizes' => ['S', 'M', 'L', 'XL'], 'colors' => ['Blue', 'Olive']],
                'description' => 'Fully seam-sealed, packable windbreaker with an adjustable storm hood.',
            ],
            [
                'name' => 'Adidas Originals Graphic Tee',
                'category' => 'fashion',
                'brand' => 'adidas',
                'emoji' => '👚',
                'price' => 34.99,
                'compare' => 44.99,
                'is_deal' => true,
                'rating' => 4.40,
                'reviews' => 260,
                'options' => ['sizes' => ['S', 'M', 'L', 'XL'], 'colors' => ['White', 'Black']],
                'description' => 'Soft cotton jersey tee with a vintage trefoil graphic and relaxed fit.',
            ],
            [
                'name' => 'New Balance 574 Classic Sneakers',
                'category' => 'fashion',
                'brand' => 'new-balance',
                'emoji' => '👟',
                'price' => 119.00,
                'rating' => 4.70,
                'reviews' => 305,
                'options' => ['sizes' => ['7', '8', '9', '10', '11'], 'colors' => ['Grey', 'Navy']],
                'description' => 'The timeless 80s runner with ENCAP midsole cushioning and suede overlays.',
            ],
            [
                'name' => 'Asics Sportstyle Running Cap',
                'category' => 'fashion',
                'brand' => 'asics',
                'emoji' => '🧢',
                'price' => 24.50,
                'rating' => 4.20,
                'reviews' => 66,
                'description' => 'Ultralight ventilated cap with a moisture-wicking sweatband and adjustable back closure.',
            ],
            [
                'name' => 'Columbia Steens Fleece Pullover',
                'category' => 'fashion',
                'brand' => 'columbia',
                'emoji' => '🧣',
                'price' => 74.00,
                'rating' => 4.60,
                'reviews' => 141,
                'options' => ['sizes' => ['S', 'M', 'L', 'XL'], 'colors' => ['Charcoal', 'Sand']],
                'description' => 'Plush microfleece pullover with a full-zip chest pocket — an everyday layering staple.',
            ],

            // ---------------------------------------------------------------- Health & Wellness
            [
                'name' => 'Xiaomi Mi Smart Body Scale',
                'category' => 'health-wellness',
                'brand' => 'xiaomi',
                'emoji' => '⚖️',
                'price' => 42.00,
                'rating' => 4.50,
                'reviews' => 198,
                'description' => '13 essential body metrics with app sync, high-precision sensors and a crisp LED display.',
            ],
            [
                'name' => 'Aroma Mist Diffuser Lamp',
                'category' => 'health-wellness',
                'emoji' => '🕯️',
                'price' => 36.90,
                'rating' => 4.60,
                'reviews' => 132,
                'description' => 'Warm wood-grain diffuser with a dimmable lamp, colour modes and auto shut-off.',
            ],
            [
                'name' => 'Resistance Bands Set (5 Pieces)',
                'category' => 'health-wellness',
                'brand' => 'demix',
                'emoji' => '🧘',
                'price' => 21.99,
                'compare' => 29.99,
                'is_deal' => true,
                'rating' => 4.30,
                'reviews' => 221,
                'description' => 'Five looped bands from extra-light to extra-heavy, with a carry bag and exercise guide.',
            ],
            [
                'name' => 'Insulated Steel Water Bottle 750ml',
                'category' => 'health-wellness',
                'emoji' => '🥤',
                'price' => 27.50,
                'rating' => 4.70,
                'reviews' => 410,
                'options' => ['colors' => ['Steel', 'Violet', 'Black']],
                'description' => 'Double-wall vacuum insulation keeps drinks cold for 24 hours, leak-proof sport cap.',
            ],

            // ---------------------------------------------------------------- Home
            [
                'name' => 'Minimalist LED Desk Lamp',
                'category' => 'home',
                'emoji' => '💡',
                'price' => 58.00,
                'rating' => 4.60,
                'reviews' => 89,
                'description' => 'Flicker-free LED bar with five colour temperatures, touch dimming and a USB-C charging port.',
            ],
            [
                'name' => 'Ceramic Nonstick Cookware Set (5 pc)',
                'category' => 'home',
                'emoji' => '🍳',
                'price' => 149.00,
                'rating' => 4.50,
                'reviews' => 74,
                'standard' => true,
                'pickup' => false,
                'description' => 'PFAS-free ceramic coating, even-heat aluminium bodies, oven safe up to 200°C.',
            ],
            [
                'name' => 'Cozy Knit Throw Blanket',
                'category' => 'home',
                'emoji' => '🛋️',
                'price' => 39.99,
                'compare' => 52.99,
                'is_deal' => true,
                'rating' => 4.70,
                'reviews' => 166,
                'description' => 'Chunky cable-knit throw in brushed microfibre — machine washable and sofa-ready.',
            ],
            [
                'name' => 'Botanical Scented Candle Trio',
                'category' => 'home',
                'emoji' => '🪔',
                'price' => 26.00,
                'rating' => 4.40,
                'reviews' => 95,
                'description' => 'Three soy-wax candles — eucalyptus, lavender and sea salt — with a 40-hour burn each.',
            ],

            // ---------------------------------------------------------------- Music
            [
                'name' => 'Wireless Studio Headphones Pro',
                'category' => 'music',
                'brand' => 'xiaomi',
                'emoji' => '🎧',
                'price' => 129.00,
                'badge' => 'top',
                'featured' => true,
                'rating' => 4.80,
                'reviews' => 512,
                'chips' => [4.8, 4.6, 5.0],
                'options' => ['colors' => ['Black', 'White']],
                'description' => 'Hybrid ANC, 40-hour battery and studio-tuned 40mm drivers with multipoint Bluetooth.',
            ],
            [
                'name' => 'Acoustic Guitar Starter Kit',
                'category' => 'music',
                'emoji' => '🎸',
                'price' => 199.00,
                'rating' => 4.60,
                'reviews' => 63,
                'standard' => true,
                'pickup' => false,
                'description' => 'Full-size dreadnought with solid spruce top, gig bag, tuner and spare strings.',
            ],
            [
                'name' => 'Portable Bluetooth Speaker Splashproof',
                'category' => 'music',
                'brand' => 'xiaomi',
                'emoji' => '🔊',
                'price' => 79.99,
                'compare' => 99.99,
                'is_deal' => true,
                'rating' => 4.50,
                'reviews' => 287,
                'description' => 'IPX7 waterproof speaker with deep dual drivers, 24-hour playtime and stereo pairing.',
            ],

            // ---------------------------------------------------------------- Gaming
            [
                'name' => 'RGB Mechanical Gaming Keyboard',
                'category' => 'gaming',
                'emoji' => '⌨️',
                'price' => 89.00,
                'rating' => 4.70,
                'reviews' => 331,
                'options' => ['colors' => ['Black', 'White']],
                'description' => 'Hot-swappable switches, per-key RGB, detachable USB-C cable and a machined aluminium top plate.',
            ],
            [
                'name' => 'Pro Wireless Controller Gamepad',
                'category' => 'gaming',
                'emoji' => '🎮',
                'price' => 69.00,
                'rating' => 4.60,
                'reviews' => 402,
                'description' => 'Low-latency 2.4 GHz wireless pad with remappable back paddles and hall-effect sticks.',
            ],
            [
                'name' => 'Ultralight Gaming Mouse 8K',
                'category' => 'gaming',
                'emoji' => '🖱️',
                'price' => 49.00,
                'compare' => 59.00,
                'is_deal' => true,
                'rating' => 4.50,
                'reviews' => 178,
                'description' => '58-gram honeycomb shell, 30K optical sensor and an 8000 Hz polling receiver in the box.',
            ],

            // ---------------------------------------------------------------- Art
            [
                'name' => 'Watercolor Paint Set 36 Colors',
                'category' => 'art',
                'emoji' => '🎨',
                'price' => 27.50,
                'rating' => 4.40,
                'reviews' => 118,
                'description' => 'Highly pigmented pans with a folding palette, water brush and mixing tray.',
            ],
            [
                'name' => 'Adjustable Wooden Canvas Easel',
                'category' => 'art',
                'emoji' => '🖼️',
                'price' => 55.00,
                'rating' => 4.50,
                'reviews' => 52,
                'standard' => true,
                'pickup' => false,
                'description' => 'Beechwood H-frame easel that folds flat, holding canvases up to 100 cm.',
            ],

            // ---------------------------------------------------------------- Crypto
            [
                'name' => 'Secure Element Hardware Wallet',
                'category' => 'crypto',
                'emoji' => '🔐',
                'price' => 79.00,
                'rating' => 4.80,
                'reviews' => 94,
                'description' => 'Open-source firmware, EAL6+ secure element and a bright touchscreen for on-device verification.',
            ],
            [
                'name' => 'Crypto Trader Enamel Mug',
                'category' => 'crypto',
                'emoji' => '☕',
                'price' => 14.99,
                'compare' => 19.99,
                'is_deal' => true,
                'rating' => 4.30,
                'reviews' => 205,
                'description' => 'Double-fired enamel mug with a diamond-glaze finish — dishwasher safe, laser etched chart line.',
            ],
        ];
    }
}
